name: A Year Of...
description: Spend a whole year doing something you love!
url: http://ayearof.xyz

markdown: kramdown
highlighter: rouge
permalink: /:year/:title.html
excerpt_separator: ""

# gauges_id: 503c5af6613f5d0f19000027
# google_analytics_id: UA-50755011-1

repository: https://github.com/AYearOf/ayearof.github.io
# help_url: https://github.com/jekyll/jekyll-help

timezone: America/Los_Angeles

# collections:
#   docs:
#     output: true


# gems:
#   - jekyll-feed
#   - jekyll-redirect-from

timezone: America/Chicago

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"